server:
  port:

spring:
  profiles:
    default: dev

  datasource:
    url:
    username:
    password:
    driver-class-name:

  jpa:
    defer-datasource-initialization:
    hibernate.ddl-auto:
    show-sql:
    properties:
      hibernate.format_sql:
      hibernate.default_batch_fetch_size:
    open-in-view:

  sql.init.mode:
  h2.console.enabled:

# debugging log disable
debug:

# actuator enable
management.endpoints.web.exposure.include:

#logging:
#  level:
#    site.board.boardtraining:
#    org.springframework.web.servlet:
#    org.hibernate.type.descriptor.sql.BasicBinder: